### ISSUE TITLE
It should really be getting the location of the mob

### ISSUE THREAD

**Issue by DameonOwen** [ARF-SS13/ARFS-6#180]
https://github.com/ARF-SS13/ARFS-6/blob/6d85b4b85409d89a197af7690af77efa6f7d9944/code/modules/pda/cart_apps.dm#L264

**Comment by GremlingSS** [comment]
I think if you were to be in a closet, the mob position wont work. So get turf is a safer option..? idk, plus it can open up to get the area in the future if needed.

**Comment by GremlingSS** [comment]
oh shit this issue is old. thanks fasthub for showing it in my feed reee
